=== lab-csx-ufmg/omtg2gml/study-cases/output/generate_xml_doc/conceptual-model-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="db-properties">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="db-type"/>
							<xs:element name="database"/>
							<xs:element name="username"/>
							<xs:element name="password"/>
							<xs:element name="port-number"/>
							<xs:element name="xml-doc-name"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="conceptual-model">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="classes">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="class" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name"/>
													<xs:element name="type"/>
													<xs:element name="table-name"/>
													<xs:element name="geometry-column"/>
													<xs:element name="number-of-registers"/>
													<xs:element name="attributes">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="attribute" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="name"/>
																			<xs:element name="type"/>
																			<xs:element name="column-name"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="relationships">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="relationship" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="contains"/>
																<xs:enumeration value="covers"/>
																<xs:enumeration value="overlap"/>
																<xs:enumeration value="touches"/>
																<xs:enumeration value="crosses"/>
																<xs:enumeration value="near"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="distance" type="xs:decimal" minOccurs="0"/>
													<xs:element name="unit" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="meter|m"/>
																<xs:pattern value="kilometer|km"/>
																<xs:pattern value="centimeter|cm"/>
																<xs:pattern value="millimeter|mm"/>
																<xs:pattern value="mile"/>
																<xs:pattern value="nautical|naut_mile"/>
																<xs:pattern value="foot"/>
																<xs:pattern value="inch"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="class1"/>
													<xs:element name="cardinality1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="min"/>
																<xs:element name="max"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="class2"/>
													<xs:element name="cardinality2">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="min"/>
																<xs:element name="max"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lab-csx-ufmg/omtg2gml/study-cases/output/generate_xml_doc/conceptual-model-document.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Owner\workspace\OmtgXMLSchema\output\generate_xml_doc\conceptual-model-schema.xsd">
	<db-properties>
		<db-type>oracle-spatial</db-type>
		<database>spatial</database>
		<username>brazil</username>
		<password>xxx</password>
		<port-number>1521</port-number>
		<xml-doc-name>city</xml-doc-name>
	</db-properties>
	<conceptual-model>
		<classes>
			<class>
				<name>rio</name>
				<type>line</type>
				<table-name>rio</table-name>
				<geometry-column>geom</geometry-column>
				<number-of-registers>all</number-of-registers>
				<attributes>
					<attribute>
						<name>id</name>
						<type> int</type>
						<column-name>id</column-name>
					</attribute>
					<attribute>
						<name>name</name>
						<type>string</type>
						<column-name>name</column-name>
					</attribute>
				</attributes>
			</class>
		</classes>
		<relationships>
			<relationship>
				<name>contains</name>
				<distance>100</distance>
				<unit>meter</unit>
				<class1>a</class1>
				<cardinality1>
					<min>0</min>
					<max>n</max>
				</cardinality1>
				<class2>b</class2>
				<cardinality2>
					<min>0</min>
					<max>n</max>
				</cardinality2>
			</relationship>
		</relationships>
	</conceptual-model>
</root>
